version: "3"

networks:
  xtxserver:
    driver: ${NETWORK_DRIVER}

services:
  ####### nginx #######
  nginx:
    build:
      context: ./nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
        - PHP_FPM_CONTAINER_NAME=${PHP_FPM_CONTAINER_NAME}
        - PHP_FPM_CONTAINER_PORT=${PHP_FPM_CONTAINER_PORT}
    image: ${COMPOSE_PROJECT_NAME}_nginx:${NGINX_VERSION}    
    ports:
      - 80:80
      - 801:801
    volumes:
      - ${NGINX_VHOSTS_PATH}:/etc/nginx/sites-available/
      - ${NGINX_CONFIG_PATH}laravel.conf:/etc/nginx/conf.d/laravel.conf
      - ${NGINX_CONFIG_PATH}phpcgi.conf:/etc/nginx/conf.d/phpcgi.conf
      - ${NGINX_CONFIG}:/etc/nginx/nginx.conf
      - ${SERVER_WWW_ROOT}:${CONTAINER_WWW_ROOT}
      - ${NGINX_LOG_PATH}:/var/log/nginx/
    depends_on:
      - php-fpm  
    networks: 
      - xtxserver

  ###### php-fpm ######
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - PHP_FPM_VERSION=${PHP_FPM_VERSION}
        - SERVER_WWW_ROOT=${CONTAINER_WWW_ROOT}
    image: ${COMPOSE_PROJECT_NAME}_php-fpm:${PHP_FPM_VERSION}
    volumes:
      - ${PHP_FPM_CONFIG}php-fpm${PHP_FPM_VERSION}.conf:/usr/local/etc/php-fpm.d/www.conf
      - ${SERVER_WWW_ROOT}:${CONTAINER_WWW_ROOT}
    ports:
      - 9000:9000
    networks:
      - xtxserver

  ###### redis ###########   
  #redis:
  #  build:
  #    context: ./redis
  #    args:
  #      - REDIS_VERSION=${REDIS_VERSION}
  #  privileged: true
  #  image: ${COMPOSE_PROJECT_NAME}_redis:${REDIS_VERSION}
  #  volumes:
  #    - ${REDIS_PATH}redis.conf:/etc/redis/redis.conf
  #  sysctls:
  #    - net.core.somaxconn=511
  #  ports:
  #    - 6379:6379
  #  networks:
  #    - xtxserver
